import { FindingCategory, FindingCode, FindingSeverity } from "./types";

export type FindingMeta = {
  code: FindingCode;
  category: FindingCategory;
  defaultSeverity: FindingSeverity;
  title: string;
  description: string;
  recommendation: string;
  businessImpact: string;
  effort: "LOW" | "MEDIUM" | "HIGH";
  impact: "LOW" | "MEDIUM" | "HIGH";
};

export const FINDING_REGISTRY: Record<FindingCode, FindingMeta> = {
  // ── RESILIENCE ───────────────────────────────────────────────
  THIRD_PARTY_FONTS: {
    code: "THIRD_PARTY_FONTS",
    category: "RESILIENCE",
    defaultSeverity: "LOW",
    title: "Third-party font dependencies detected",
    description: "External font services (Google Fonts, Adobe Fonts) can fail or slow down rendering if the provider is unreachable.",
    recommendation: "Use self-hosted fonts or add font-display: swap with local fallbacks.",
    businessImpact: "Font loading failures cause invisible text or layout shifts, hurting user experience.",
    effort: "LOW",
    impact: "LOW",
  },
  THIRD_PARTY_CRITICAL_JS: {
    code: "THIRD_PARTY_CRITICAL_JS",
    category: "RESILIENCE",
    defaultSeverity: "MEDIUM",
    title: "Critical JavaScript loaded from third parties",
    description: "Scripts from external domains in the <head> block rendering and depend on third-party availability.",
    recommendation: "Self-host critical scripts or add async/defer attributes. Consider loading non-critical scripts on demand.",
    businessImpact: "Third-party JS failures can break core functionality and increase page load time.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  RECAPTCHA_DEPENDENCY: {
    code: "RECAPTCHA_DEPENDENCY",
    category: "RESILIENCE",
    defaultSeverity: "LOW",
    title: "reCAPTCHA dependency detected",
    description: "Google reCAPTCHA loads external scripts and requires Google servers to be available.",
    recommendation: "Consider alternatives like hCaptcha or Turnstile that are lighter or self-hosted.",
    businessImpact: "reCAPTCHA failures prevent form submissions and user interactions.",
    effort: "MEDIUM",
    impact: "LOW",
  },

  // ── SECURITY ─────────────────────────────────────────────────
  MIXED_CONTENT: {
    code: "MIXED_CONTENT",
    category: "SECURITY",
    defaultSeverity: "HIGH",
    title: "Mixed content detected (HTTP resources on HTTPS page)",
    description: "Loading HTTP resources on an HTTPS page causes browser warnings and blocks, degrading security.",
    recommendation: "Update all resource URLs to use HTTPS. Set up redirects from HTTP to HTTPS.",
    businessImpact: "Mixed content triggers browser security warnings, blocks resources, and erodes user trust.",
    effort: "LOW",
    impact: "HIGH",
  },
  NO_CSP_HEADER: {
    code: "NO_CSP_HEADER",
    category: "SECURITY",
    defaultSeverity: "MEDIUM",
    title: "Content Security Policy (CSP) header missing",
    description: "Without CSP, the site is vulnerable to XSS attacks and unauthorized script execution.",
    recommendation: "Add a Content-Security-Policy header with appropriate directives for your resources.",
    businessImpact: "Missing CSP increases XSS risk and may fail security compliance audits.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  NO_HSTS: {
    code: "NO_HSTS",
    category: "SECURITY",
    defaultSeverity: "MEDIUM",
    title: "HTTP Strict Transport Security (HSTS) header missing",
    description: "Without HSTS, browsers may accept HTTP connections, leaving users vulnerable to downgrade attacks.",
    recommendation: "Add Strict-Transport-Security header with max-age of at least 31536000 (1 year).",
    businessImpact: "Missing HSTS allows man-in-the-middle attacks and reduces browser security indicators.",
    effort: "LOW",
    impact: "MEDIUM",
  },

  // ── PERFORMANCE ──────────────────────────────────────────────
  STATIC_ASSETS_NO_LONG_CACHE: {
    code: "STATIC_ASSETS_NO_LONG_CACHE",
    category: "PERFORMANCE",
    defaultSeverity: "LOW",
    title: "Static assets missing long cache headers",
    description: "Scripts, styles, and images without long cache headers force repeated downloads on every visit.",
    recommendation: "Set Cache-Control headers with long max-age (1 year) for immutable assets with hashed filenames.",
    businessImpact: "Missing caching increases page load time and bandwidth costs for returning visitors.",
    effort: "LOW",
    impact: "LOW",
  },
  SLOW_TTFB_OR_SERVER_RESPONSE: {
    code: "SLOW_TTFB_OR_SERVER_RESPONSE",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Slow server response time detected",
    description: "Time to First Byte (TTFB) exceeds acceptable thresholds, indicating server-side performance issues.",
    recommendation: "Optimize server response time: use caching, CDN, database query optimization, or server-side rendering.",
    businessImpact: "Slow TTFB directly impacts Core Web Vitals and user perceived performance.",
    effort: "HIGH",
    impact: "HIGH",
  },
  TOO_MANY_REQUESTS_OR_HEAVY_PAGE: {
    code: "TOO_MANY_REQUESTS_OR_HEAVY_PAGE",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Excessive number of HTTP requests detected",
    description: "Pages with many resources take longer to load due to connection overhead and rendering delays.",
    recommendation: "Bundle assets, use HTTP/2 multiplexing, lazy-load below-the-fold content, and reduce third-party scripts.",
    businessImpact: "Too many requests increase load time, especially on mobile and slow networks.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  SLOW_SERVER_TTFB: {
    code: "SLOW_SERVER_TTFB",
    category: "PERFORMANCE",
    defaultSeverity: "HIGH",
    title: "Very slow server TTFB (>2s)",
    description: "Server takes over 2 seconds to send the first byte of HTML, indicating severe performance issues.",
    recommendation: "Investigate server-side bottlenecks: database queries, API calls, rendering time. Consider CDN or static generation.",
    businessImpact: "Extremely slow TTFB causes high bounce rates and poor search rankings.",
    effort: "HIGH",
    impact: "HIGH",
  },
  SLOW_SERVER_RESPONSE: {
    code: "SLOW_SERVER_RESPONSE",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Slow server response time detected",
    description: "Total server response time exceeds optimal thresholds.",
    recommendation: "Optimize server-side code, enable compression, use a CDN, and implement caching strategies.",
    businessImpact: "Slow responses frustrate users and increase abandonment rates.",
    effort: "HIGH",
    impact: "MEDIUM",
  },
  CWV_LCP_POOR_PROXY: {
    code: "CWV_LCP_POOR_PROXY",
    category: "PERFORMANCE",
    defaultSeverity: "HIGH",
    title: "Largest Contentful Paint (LCP) likely poor",
    description: "Server-side indicators suggest LCP exceeds 4 seconds, failing Core Web Vitals thresholds.",
    recommendation: "Optimize LCP: preload hero images, use next-gen formats (WebP/AVIF), reduce server response time.",
    businessImpact: "Poor LCP directly impacts Google search rankings and user experience scores.",
    effort: "MEDIUM",
    impact: "HIGH",
  },
  CWV_FID_POOR_PROXY: {
    code: "CWV_FID_POOR_PROXY",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "First Input Delay (FID) likely poor",
    description: "Heavy third-party scripts or large bundles suggest FID may exceed 200ms thresholds.",
    recommendation: "Reduce JavaScript execution time: code-split, defer non-critical scripts, use web workers.",
    businessImpact: "Poor FID makes pages feel unresponsive to user interactions.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  CWV_CLS_POOR_PROXY: {
    code: "CWV_CLS_POOR_PROXY",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Cumulative Layout Shift (CLS) likely poor",
    description: "Missing image dimensions, dynamic content injection, or late-loading fonts can cause layout shifts.",
    recommendation: "Set explicit width/height on images, use CSS aspect-ratio, reserve space for dynamic content.",
    businessImpact: "Layout shifts frustrate users and can cause accidental clicks on wrong elements.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  CWV_OVERALL_NEEDS_IMPROVEMENT: {
    code: "CWV_OVERALL_NEEDS_IMPROVEMENT",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Core Web Vitals need improvement",
    description: "Overall Core Web Vitals performance is in the 'needs improvement' range.",
    recommendation: "Address individual CWV issues: optimize LCP, reduce FID, minimize CLS.",
    businessImpact: "Suboptimal CWV scores affect search ranking and user satisfaction.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  CWV_OVERALL_GOOD_PROXY: {
    code: "CWV_OVERALL_GOOD_PROXY",
    category: "PERFORMANCE",
    defaultSeverity: "INFO",
    title: "Core Web Vitals appear good",
    description: "Server-side indicators suggest Core Web Vitals are within acceptable thresholds.",
    recommendation: "Continue monitoring. Consider running real-user monitoring for accurate measurements.",
    businessImpact: "Good CWV scores support better search rankings and user experience.",
    effort: "LOW",
    impact: "LOW",
  },
  IMAGES_MISSING_LAZY_LOADING: {
    code: "IMAGES_MISSING_LAZY_LOADING",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Images missing lazy loading",
    description: "Below-the-fold images without loading=\"lazy\" are loaded immediately, wasting bandwidth.",
    recommendation: "Add loading=\"lazy\" to images below the fold. Keep above-the-fold images eager-loaded.",
    businessImpact: "Missing lazy loading increases initial page load time and data usage on mobile.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  IFRAMES_MISSING_LAZY_LOADING: {
    code: "IFRAMES_MISSING_LAZY_LOADING",
    category: "PERFORMANCE",
    defaultSeverity: "LOW",
    title: "Iframes missing lazy loading",
    description: "Embedded content (videos, maps) without lazy loading loads immediately.",
    recommendation: "Add loading=\"lazy\" to iframes below the fold.",
    businessImpact: "Embedded content is often heavy and delays page rendering.",
    effort: "LOW",
    impact: "LOW",
  },
  SCRIPTS_MISSING_ASYNC_DEFER: {
    code: "SCRIPTS_MISSING_ASYNC_DEFER",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Scripts missing async or defer attributes",
    description: "Synchronous scripts in <head> block page rendering until downloaded and executed.",
    recommendation: "Add async or defer to non-critical scripts. Keep only critical inline scripts synchronous.",
    effort: "LOW",
    impact: "MEDIUM",
    businessImpact: "Synchronous scripts delay page rendering and First Contentful Paint.",
  },
  LAZY_LOADING_IMPLEMENTED: {
    code: "LAZY_LOADING_IMPLEMENTED",
    category: "PERFORMANCE",
    defaultSeverity: "INFO",
    title: "Lazy loading is implemented",
    description: "Images and/or iframes use lazy loading for better performance.",
    recommendation: "No action needed. Lazy loading is correctly implemented.",
    businessImpact: "Lazy loading reduces initial page load and improves performance scores.",
    effort: "LOW",
    impact: "LOW",
  },
  PERF_DIAGNOSTIC_RENDER_PATH_RISK: {
    code: "PERF_DIAGNOSTIC_RENDER_PATH_RISK",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Render path resources may delay rendering",
    description: "Critical resources in the render path can block above-the-fold content from painting quickly.",
    recommendation: "Inline critical CSS, defer non-critical scripts, and preload above-the-fold resources.",
    businessImpact: "Render-blocking resources increase Largest Contentful Paint and First Contentful Paint times.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  PERF_DIAGNOSTIC_SCRIPT_BLOCKING_RISK: {
    code: "PERF_DIAGNOSTIC_SCRIPT_BLOCKING_RISK",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Blocking third-party scripts detected",
    description: "Synchronous third-party scripts block HTML parsing and delay page rendering.",
    recommendation: "Add async/defer attributes, use dynamic imports, or move scripts to the end of the body.",
    businessImpact: "Blocking scripts increase Total Blocking Time and delay user interactions.",
    effort: "MEDIUM",
    impact: "MEDIUM",
  },
  PERF_DIAGNOSTIC_LAYOUT_STABILITY_RISK: {
    code: "PERF_DIAGNOSTIC_LAYOUT_STABILITY_RISK",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Images without explicit dimensions detected",
    description: "Images without width and height attributes cause layout shifts as they load.",
    recommendation: "Set explicit width and height attributes on all images, or use CSS aspect-ratio.",
    businessImpact: "Layout shifts frustrate users and increase Cumulative Layout Shift scores.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  PERFORMANCE_EVIDENCE_UNAVAILABLE: {
    code: "PERFORMANCE_EVIDENCE_UNAVAILABLE",
    category: "PERFORMANCE",
    defaultSeverity: "MEDIUM",
    title: "Performance evidence unavailable",
    description: "Provider-based performance evidence could not be collected for this URL.",
    recommendation: "Configure a PageSpeed Insights API key or use alternative performance monitoring tools.",
    businessImpact: "Without performance evidence, the audit cannot provide Core Web Vitals insights.",
    effort: "LOW",
    impact: "MEDIUM",
  },

  // ── SEO ──────────────────────────────────────────────────────
  SEO_BASICS_MISSING: {
    code: "SEO_BASICS_MISSING",
    category: "SEO",
    defaultSeverity: "HIGH",
    title: "Essential SEO elements missing",
    description: "The page is missing one or more critical SEO elements: title tag, meta description, canonical URL, or Open Graph tags.",
    recommendation: "Add a unique title tag (50-60 chars), meta description (150-160 chars), canonical URL, and Open Graph tags.",
    businessImpact: "Missing SEO basics directly reduce search visibility and click-through rates.",
    effort: "LOW",
    impact: "HIGH",
  },
  NO_ROBOTS_TXT: {
    code: "NO_ROBOTS_TXT",
    category: "SEO",
    defaultSeverity: "MEDIUM",
    title: "robots.txt file not found",
    description: "Without robots.txt, search engines may crawl unintended pages or miss important ones.",
    recommendation: "Create a robots.txt file with appropriate allow/disallow rules and sitemap reference.",
    businessImpact: "Missing robots.txt can lead to crawling budget waste or unintended indexing.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  NO_SITEMAP: {
    code: "NO_SITEMAP",
    category: "SEO",
    defaultSeverity: "MEDIUM",
    title: "XML sitemap not found",
    description: "Without a sitemap, search engines may not discover all important pages.",
    recommendation: "Create an XML sitemap and submit it to Google Search Console and Bing Webmaster Tools.",
    businessImpact: "Missing sitemaps slow down page discovery and indexing by search engines.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  NO_SCHEMA_ORG: {
    code: "NO_SCHEMA_ORG",
    category: "SEO",
    defaultSeverity: "LOW",
    title: "No structured data (Schema.org) found",
    description: "Without structured data, the page misses opportunities for rich snippets in search results.",
    recommendation: "Add relevant Schema.org JSON-LD markup for your content type (Article, Product, FAQ, etc.).",
    businessImpact: "Structured data enables rich snippets, improving search visibility and click-through rates.",
    effort: "LOW",
    impact: "LOW",
  },
  SCHEMA_ORG_PRESENT: {
    code: "SCHEMA_ORG_PRESENT",
    category: "SEO",
    defaultSeverity: "INFO",
    title: "Structured data (Schema.org) found",
    description: "The page includes Schema.org JSON-LD markup.",
    recommendation: "Verify the markup using Google Rich Results Test for accuracy.",
    businessImpact: "Well-implemented structured data improves search result appearance.",
    effort: "LOW",
    impact: "LOW",
  },
  SCHEMA_ORG_NO_RECOMMENDED_TYPES: {
    code: "SCHEMA_ORG_NO_RECOMMENDED_TYPES",
    category: "SEO",
    defaultSeverity: "LOW",
    title: "Structured data present but missing recommended types",
    description: "The page has structured data but not the most relevant types for its content.",
    recommendation: "Add recommended Schema.org types based on your content: Organization, WebSite, BreadcrumbList, etc.",
    businessImpact: "Missing recommended types limits rich snippet opportunities.",
    effort: "LOW",
    impact: "LOW",
  },
  SCHEMA_ORG_ERRORS: {
    code: "SCHEMA_ORG_ERRORS",
    category: "SEO",
    defaultSeverity: "MEDIUM",
    title: "Structured data has errors",
    description: "Schema.org markup contains validation errors that prevent search engines from using it.",
    recommendation: "Fix validation errors using Google Rich Results Test. Ensure required properties are present.",
    businessImpact: "Invalid structured data is ignored by search engines, wasting implementation effort.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  SCHEMA_ORG_WARNINGS: {
    code: "SCHEMA_ORG_WARNINGS",
    category: "SEO",
    defaultSeverity: "INFO",
    title: "Structured data has warnings",
    description: "Schema.org markup has non-critical issues that could be improved.",
    recommendation: "Address warnings to maximize structured data effectiveness. Use Google Rich Results Test.",
    businessImpact: "Warnings don't block rich snippets but may reduce their quality.",
    effort: "LOW",
    impact: "LOW",
  },

  // ── ACCESSIBILITY ────────────────────────────────────────────
  IMG_MISSING_ALT: {
    code: "IMG_MISSING_ALT",
    category: "ACCESSIBILITY",
    defaultSeverity: "MEDIUM",
    title: "Images missing alt text",
    description: "Images without alt attributes are invisible to screen readers and search engines.",
    recommendation: "Add descriptive alt text to all meaningful images. Use alt=\"\" for decorative images.",
    businessImpact: "Missing alt text excludes visually impaired users and hurts image SEO.",
    effort: "LOW",
    impact: "MEDIUM",
  },
  IMG_EMPTY_ALT_MANY: {
    code: "IMG_EMPTY_ALT_MANY",
    category: "ACCESSIBILITY",
    defaultSeverity: "LOW",
    title: "Many images with empty alt text",
    description: "A high number of images have empty alt attributes, which may indicate missing content descriptions.",
    recommendation: "Review images with alt=\"\" — decorative images should use empty alt, but content images need descriptions.",
    businessImpact: "Excessive empty alt text reduces accessibility and image search visibility.",
    effort: "LOW",
    impact: "LOW",
  },
  INPUT_MISSING_LABEL: {
    code: "INPUT_MISSING_LABEL",
    category: "ACCESSIBILITY",
    defaultSeverity: "HIGH",
    title: "Form inputs missing labels",
    description: "Form inputs without associated labels are inaccessible to screen readers and difficult to use.",
    recommendation: "Add <label> elements with for attributes, or use aria-label/aria-labelledby on inputs.",
    businessImpact: "Unlabeled inputs make forms unusable for assistive technology users.",
    effort: "LOW",
    impact: "HIGH",
  },
};

export function getFindingMeta(code: FindingCode): FindingMeta {
  return FINDING_REGISTRY[code];
}

export function getAllFindingCodes(): FindingCode[] {
  return Object.keys(FINDING_REGISTRY) as FindingCode[];
}

export function getFindingsByCategory(category: FindingCategory): FindingMeta[] {
  return Object.values(FINDING_REGISTRY).filter((f) => f.category === category);
}

export function getFindingsBySeverity(severity: FindingSeverity): FindingMeta[] {
  return Object.values(FINDING_REGISTRY).filter((f) => f.defaultSeverity === severity);
}
